sudo: false

language: haskell

# Yes, this is setting systemwide version. Other way Travis updates 7.x to 7.10.x. And direct usage of 8.0 is undocumented feature. GHC 8.0.2 allready instaled in the /opt/ by the Travis team, but that is not documented anywhere.
ghc:
  - 8.0

# Speeding-up GIT pulls. If set to 1 - Travis builds would go only consequentially
git:
  depth: 3

cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/build/serokell/importify/.stack-work"

addons:
  apt:
    sources:
      - sourceline: 'ppa:hvr/ghc' # Canonical Trusty repo is ancient. This is relevant Haskell repo, just in case.
    packages:
      - libgmp-dev
      - ghc-8.0.2
      - cabal-install-2.0

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version

install:
  ### To allow some step to fail. Like for purpose to build-up cache. Add ` || true` to the end of a line.

  # Prepare Haskell environment for current project
  - travis_wait 30 stack setup --no-terminal

  # Just in case, check that external GHC disabled
  - stack config set system-ghc --global false || true

  # Build project dependencies
  - travis_wait 40 stack build --only-dependencies --no-terminal || true

  # Build project itself
  ## Compile with tests and benchmarks, but does not run executable.
  - travis_wait 40 stack build --test --bench --no-run-tests --no-run-benchmarks --no-terminal

  # You can test `allow_failures` with it
  #- false
script:
  # Run tests
  - travis_wait 40 stack test --no-terminal

  # You can force Travis to skip his default tries to help you in main `script` with it:
  #- true
notifications:
  email: false
  slack:
    rooms:
      - serokell:JWBvWb5PKOhknocQgcoQnflZ
    on_success: always
    on_failure: always
